CREATE TABLE doodle_user
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(255) NOT NULL UNIQUE,
    username varchar(255) NOT NULL
);

CREATE TABLE calendar
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES doodle_user (id)
);

CREATE TABLE time_slot
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id bigint      NOT NULL REFERENCES calendar (id),
    start_time  timestamptz NOT NULL,
    end_time    timestamptz NOT NULL,
    status      varchar(10) NOT NULL,
    version     bigint      NOT NULL DEFAULT 0,
    CONSTRAINT chk_slot_time_order CHECK (end_time > start_time)
);

CREATE INDEX idx_time_slot_calendar_start ON time_slot (calendar_id, start_time);

CREATE TABLE meeting
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id     bigint       NOT NULL UNIQUE REFERENCES time_slot (id),
    title       varchar(255) NOT NULL,
    description varchar(1500)
);

CREATE TABLE meeting_participant
(
    meeting_id bigint NOT NULL REFERENCES meeting (id) ON DELETE CASCADE,
    user_id    bigint NOT NULL REFERENCES doodle_user (id),
    PRIMARY KEY (meeting_id, user_id)
);

CREATE INDEX idx_meeting_participant_user ON meeting_participant (user_id);